name = input ("What is your name ")
print (f"Hello {name} I want to learn about you.")
print("whats your favorite sport")
input()
print("oh i like that sport to!")
print("Whats your favorie color")
input()
print("mine is blue")
print("hows your day been")
input()
print("thats good ")
name = input("whats your worst injury ever")
print(f"Oh i would hate if {name} happend to me")
print("anyway im going to shut down now bye")