name = input ("What is your name ")
print (f"Hello {name} and i wan't to learn about you.")
print("whats your favorite sport")
input()
print("oh i like that sport to!")
print("Whats your favorie color")
input()
print("mine is blue")
print("hows your day been")
input()
print("thats good ")
 print("Am I real")
input("")